version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Localstack endpoint
    environment:
      - SERVICES=s3:4566
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"